version: "3"
services:
  gatsby:
    command: ["gatsby", "develop", "--host", "0.0.0.0"]
    volumes:
      - ./src:/home/gatsby-app/src
      - ./.cache:/home/gatsby-app/.cache
      - ./gatsby-browser.js:/home/gatsby-app/gatsby-browser.js
      - ./gatsby-config.js:/home/gatsby-app/gatsby-config.js
      - ./gatsby-node.js:/home/gatsby-app/gatsby-node.js
      - ./gatsby-ssr.js:/home/gatsby-app/gatsby-ssr.js
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
  wordpress:
    stdin_open: true
    tty: true
  db:
    stdin_open: true
    tty: true
